coverage:
  range: 70..90
  round: down
  precision: 2
  status:
    project:
      fastwarc:
        threshold: 2%
        paths:
          - tests/fastwarc
          - fastwarc
      products:
        threshold: 2%
        resiliparse:
          - tests/resiliparse
          - resiliparse
comment:
  require_changes: true
