set(VCPKG_TARGET_ARCHITECTURE x64)

set(VCPKG_BUILD_TYPE release)
set(VCPKG_C_FLAGS "/O2")
set(VCPKG_CXX_FLAGS "/std:c++latest /O2")
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
if(PORT MATCHES "abseil")
    set(VCPKG_LIBRARY_LINKAGE static)
endif()
