# Copyright 2024 Janek Bevendorff
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from typing import Optional, overload, Sequence
from typing_extensions import deprecated

from .node import AttrNode, ElementNode, Node


class DOMCollection(Sequence[Node]):
    @deprecated('Use DocumentNode.get_element_by_id() instead')
    def get_element_by_id(self, element_id: str, case_insensitive: bool = False) -> Optional[Node]: ...
    def get_elements_by_attr(self, attr_name: str, attr_value: str, case_insensitive: bool = False) -> DOMCollection[Node]: ...
    def get_elements_by_class_name(self, class_name: str) -> DOMCollection[Node]: ...
    def get_elements_by_tag_name(self, tag_name: str) -> DOMCollection[Node]: ...
    def query_selector(self, selector: str) -> Optional[Node]: ...
    def query_selector_all(self, selector: str) -> DOMCollection[Node]: ...
    def matches(self, selector: str) -> bool: ...

    @overload
    def __getitem__(self, index: int) -> Node: ...
    @overload
    def __getitem__(self, index: slice) -> Sequence[Node]: ...
    def __len__(self) -> int: ...


class DOMElementClassList(Sequence[str]):
    def add(self, class_name: str): ...
    def remove(self, class_name: str): ...

    @overload
    def __getitem__(self, index: int) -> str: ...
    @overload
    def __getitem__(self, index: slice) -> Sequence[str]: ...
    def __len__(self) -> int: ...


class NodeList(Sequence[Node]): ...
class ElementNodeList(Sequence[ElementNode]): ...
class NamedNodeMap(Sequence[AttrNode]): ...
HTMLCollection = ElementNodeList

class DOMTokenList(Sequence[str]): ...
