[workspace]
resolver = "2"
members = [
  "lib"
]

[workspace.package]
version = "0.0.0"
edition = "2021"
publish = false
description = "Resiliparse Rust bindings"
authors = ["Janek Bevendorff"]

[workspace.dependencies]
pyo3 = { version = "^0.22.2", features = ["extension-module"] }
