name: Publish Artifacts

on:
  workflow_run:
    workflows: [ "Build Wheels" ]
    types:
      - completed
    tags:
      - 'v*'
    branches:
      - develop

jobs:
  publish-wheels:
    runs-on: ubuntu-latest
    needs: build-documentation
    if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Download Wheels
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          name: wheels

      - name: Download Source Dist
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          name: sdist

      - name: Publish Wheels
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD1: ${{ secrets.PYPI_FASTWARC_API_TOKEN }}
          TWINE_PASSWORD2: ${{ secrets.PYPI_RESILIPARSE_API_TOKEN }}
        run: |
          set -e

          python3 -m pip install twine

          TWINE_PASSWORD="$TWINE_PASSWORD1" python3 -m twine upload FastWARC-*.whl FastWARC-*.tar.gz
          TWINE_PASSWORD="$TWINE_PASSWORD2" python3 -m twine upload Resiliparse-*.whl Resiliparse-*.tar.gz

  trigger-rtd-build:
    runs-on: ubuntu-latest
    needs: publish-wheels
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Trigger Readthedocs Build
        uses: dfm/rtds-action@v1
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}
